version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: crud
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    volumes:
      - "/srv/mysql/data:/var/lib/mysql"
  
 